#!/usr/bin/env python3
"""
scripts/football_records_coverage.py

Completeness check for the weekly football records.

Every competition/gameweek is expected to produce FOUR artefacts:

  1_model.*         full-round model prices: 1X2 + O/U 2.5          (pre-round)
  2_bets.*          +EV vs market, with matrix confluence            (pre-round)
  3_review_model.*  model vs market — CLV and ROI                    (post-round)
  4_review_bets.*   bets — CLV and ROI                               (post-round)

The gameweek calendar is DERIVED FROM PLAYED RESULTS, not from a hand-kept list,
so a round cannot silently go missing: as soon as football-data publishes the
fixtures, the round appears here and any absent artefact shows as a gap.

A round that genuinely produced no qualifying bets is not a gap — record it with
a `2_bets_none.md` stating why, and it counts as satisfied.

Writes outputs/football/COVERAGE.md and exits 1 if anything is missing, so it can
gate a weekly job.

Run: python3 scripts/football_records_coverage.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
FOOT = ROOT / "outputs/football"
SEASON = "2026/27"
SEASON_DIR = "2026-27"

COMPS = {
    "epl":          ("EPL",              ROOT / "ml/football/data/epl/matches/epl_matches.csv", "gw"),
    "championship": ("EFL Championship", ROOT / "ml/football/data/championship/matches/championship_matches.csv", "gw"),
    "ucl":          ("UCL",              None, "md"),
}
SLOTS = [
    ("1_model",        "Model (1X2 + O/U 2.5)"),
    ("2_bets",         "Bets (+EV / matrix)"),
    ("3_review_model", "Review: model vs market"),
    ("4_review_bets",  "Review: bets CLV/ROI"),
]


def rounds_from_results(csv_path: Path) -> list[tuple[int, str, str, int]]:
    """Derive played rounds by chunking the season's matches into full rounds."""
    df = pd.read_csv(csv_path, low_memory=False)
    s = df[df.Season == SEASON].copy()
    if s.empty:
        return []
    s["D"] = pd.to_datetime(s.Date, errors="coerce")
    s = s.sort_values("D")
    per = len({*s.HomeTeam, *s.AwayTeam}) // 2
    out = []
    for i in range(0, len(s), per):
        c = s.iloc[i:i + per]
        out.append((i // per + 1, str(c.D.min().date()), str(c.D.max().date()), len(c)))
    return out


def has_slot(d: Path, prefix: str) -> bool:
    if not d.exists():
        return False
    if prefix == "2_bets" and any(d.glob("2_bets_none*")):
        return True
    return any(f.name.startswith(prefix) for f in d.iterdir() if f.is_file())


def main() -> None:
    lines = ["# Football records coverage", "",
             f"Season **{SEASON}** · generated by `scripts/football_records_coverage.py`", "",
             "Rounds are derived from played results, so a missing round cannot hide. A round",
             "that produced no qualifying bets should carry a `2_bets_none.md` — that counts",
             "as satisfied, not as a gap.", ""]
    total = filled = 0
    gaps: list[str] = []

    for key, (label, csv_path, prefix) in COMPS.items():
        lines += [f"## {label}", ""]
        if csv_path is None or not csv_path.exists():
            base = FOOT / key / SEASON_DIR
            found = sorted(p.name for p in base.glob(f"{prefix}*")) if base.exists() else []
            lines += [f"No results feed wired for {label}; cannot derive a round calendar.",
                      f"Directories present: {', '.join(found) if found else 'none'}.", ""]
            continue

        rounds = rounds_from_results(csv_path)
        if not rounds:
            lines += ["No rounds played yet this season.", ""]
            continue

        lines += ["| Round | Dates | Matches | " + " | ".join(t for _, t in SLOTS) + " | Status |",
                  "|---|---|---:|" + ":--:|" * len(SLOTS) + "---|"]
        for num, d0, d1, n in rounds:
            d = FOOT / key / SEASON_DIR / f"{prefix}{num:02d}"
            marks, ok = [], True
            for slot, _ in SLOTS:
                good = has_slot(d, slot)
                marks.append("✅" if good else "❌")
                total += 1
                if good:
                    filled += 1
                else:
                    ok = False
                    gaps.append(f"{label} {prefix.upper()}{num:02d} — missing `{slot}`")
            lines.append(f"| {prefix.upper()}{num:02d} | {d0} → {d1} | {n} | " +
                         " | ".join(marks) + " | " + ("complete" if ok else "**GAP**") + " |")
        lines.append("")

    pct = filled / total * 100 if total else 0.0
    lines += ["---", "", "## Summary", "",
              f"**{filled}/{total} artefacts present ({pct:.1f}%)**", ""]
    if gaps:
        lines += [f"### {len(gaps)} gaps", ""] + [f"- {g}" for g in gaps] + [""]
    else:
        lines += ["No gaps. Every played round has all four artefacts.", ""]

    (FOOT / "COVERAGE.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"written: {(FOOT / 'COVERAGE.md').relative_to(ROOT)}")
    sys.exit(1 if gaps else 0)


if __name__ == "__main__":
    main()
